// AUTO-GENERATED by gen-webp.mjs (Section 7). Do not edit by hand.
// Per-card local WebP covers (q=80) staged in public/images. Sized to COVER the 1440 card box;
// DPR (x) descriptors select 1x at DPR1 (fidelity) and 2x at DPR2. object-fit:cover crops to the box.
export interface CaseCover {
  src: string;
  w: number;
  h: number;
  src2x?: string;
  w2?: number;
  h2?: number;
}

export const CASE_COVERS: Record<string, CaseCover> = {
  "suitsupply": {"src":"/images/suitsupply.webp","w":800,"h":502,"src2x":"/images/suitsupply@2x.webp","w2":1599,"h2":1004},
  "bloom-wolf": {"src":"/images/bloom-wolf.webp","w":741,"h":502,"src2x":"/images/bloom-wolf@2x.webp","w2":1483,"h2":1004},
  "akris": {"src":"/images/akris.webp","w":803,"h":502,"src2x":"/images/akris@2x.webp","w2":1606,"h2":1004},
  "x-bionic": {"src":"/images/x-bionic.webp","w":512,"h":768,"src2x":"/images/x-bionic@2x.webp","w2":1024,"h2":1536},
  "mammut": {"src":"/images/mammut.webp","w":753,"h":502,"src2x":"/images/mammut@2x.webp","w2":1506,"h2":1004},
  "foam-platform": {"src":"/images/foam-platform.webp","w":512,"h":768,"src2x":"/images/foam-platform@2x.webp","w2":1024,"h2":1535},
  "expedition-baikal": {"src":"/images/expedition-baikal.webp","w":753,"h":502,"src2x":"/images/expedition-baikal@2x.webp","w2":1507,"h2":1004},
  "powerhouse-company": {"src":"/images/powerhouse-company.webp","w":793,"h":502,"src2x":"/images/powerhouse-company@2x.webp","w2":1586,"h2":1004},
  "mollie": {"src":"/images/mollie.webp","w":886,"h":502,"src2x":"/images/mollie@2x.webp","w2":1772,"h2":1004},
  "polaroid": {"src":"/images/polaroid.webp","w":669,"h":446,"src2x":"/images/polaroid@2x.webp","w2":1338,"h2":892},
  "x-bionic-terraskin": {"src":"/images/x-bionic-terraskin.webp","w":512,"h":768,"src2x":"/images/x-bionic-terraskin@2x.webp","w2":1024,"h2":1536},
  "adidas": {"src":"/images/adidas.webp","w":669,"h":446,"src2x":"/images/adidas@2x.webp","w2":1338,"h2":892},
  "klabu": {"src":"/images/klabu.webp","w":512,"h":768,"src2x":"/images/klabu@2x.webp","w2":1024,"h2":1535},
  "bezier": {"src":"/images/bezier.webp","w":787,"h":446,"src2x":"/images/bezier@2x.webp","w2":1574,"h2":892},
  "rocycle": {"src":"/images/rocycle.webp","w":512,"h":506,"src2x":"/images/rocycle@2x.webp","w2":1024,"h2":1013},
  "foam-talent-2020": {"src":"/images/foam-talent-2020.webp","w":668,"h":446,"src2x":"/images/foam-talent-2020@2x.webp","w2":1336,"h2":892},
  "abel-vita-odor": {"src":"/images/abel-vita-odor.webp","w":669,"h":446,"src2x":"/images/abel-vita-odor@2x.webp","w2":1338,"h2":892},
  "vitra-gift-finder": {"src":"/images/vitra-gift-finder.webp","w":787,"h":446,"src2x":"/images/vitra-gift-finder@2x.webp","w2":1573,"h2":892},
  "roger-vivier": {"src":"/images/roger-vivier.webp","w":512,"h":683,"src2x":"/images/roger-vivier@2x.webp","w2":1024,"h2":1366},
  "polaroid-i-2": {"src":"/images/polaroid-i-2.webp","w":719,"h":446,"src2x":"/images/polaroid-i-2@2x.webp","w2":1439,"h2":892},
  "the-balvenie": {"src":"/images/the-balvenie.webp","w":669,"h":446,"src2x":"/images/the-balvenie@2x.webp","w2":1338,"h2":892},
  "land-of-ride": {"src":"/images/land-of-ride.webp","w":787,"h":446,"src2x":"/images/land-of-ride@2x.webp","w2":1574,"h2":892},
  "secrid": {"src":"/images/secrid.webp","w":512,"h":296,"src2x":"/images/secrid@2x.webp","w2":1024,"h2":591},
  "foam-talent-2021": {"src":"/images/foam-talent-2021.webp","w":512,"h":765,"src2x":"/images/foam-talent-2021@2x.webp","w2":1024,"h2":1530},
  "moooi": {"src":"/images/moooi.webp","w":512,"h":640,"src2x":"/images/moooi@2x.webp","w2":1024,"h2":1280},
  "alpine": {"src":"/images/alpine.webp","w":512,"h":649,"src2x":"/images/alpine@2x.webp","w2":1024,"h2":1297},
  "just-brands": {"src":"/images/just-brands.webp","w":886,"h":502,"src2x":"/images/just-brands@2x.webp","w2":1772,"h2":1004},
  "ark8": {"src":"/images/ark8.webp","w":512,"h":640,"src2x":"/images/ark8@2x.webp","w2":1024,"h2":1280},
  "ace-and-tate": {"src":"/images/ace-and-tate.webp","w":512,"h":640,"src2x":"/images/ace-and-tate@2x.webp","w2":1024,"h2":1281},
  "koleksiyon": {"src":"/images/koleksiyon.webp","w":886,"h":502,"src2x":"/images/koleksiyon@2x.webp","w2":1771,"h2":1004},
  "studio-job": {"src":"/images/studio-job.webp","w":812,"h":502,"src2x":"/images/studio-job@2x.webp","w2":1623,"h2":1004},
  "stellar-development": {"src":"/images/stellar-development.webp","w":512,"h":325,"src2x":"/images/stellar-development@2x.webp","w2":1024,"h2":650},
  "vitra": {"src":"/images/vitra.webp","w":886,"h":502,"src2x":"/images/vitra@2x.webp","w2":1772,"h2":1004},
};
